# configure-applications.yml

---
  - name: Setup Database Server
    hosts: db_servers
    gather_facts: true
    become: yes
    become_method: sudo
    remote_user: ec2-user
    connection: ssh  
    roles:
      - mysqldb

  - name: Setup Webserver
    hosts: web_servers
    gather_facts: true
    become: yes
    become_method: sudo
    remote_user: ec2-user
    connection: ssh 
    roles:
      - python-rhel
      - flaskapp



 
      



